### ISSUE TITLE
Link "Bug XXXXX" in text to Bugzilla bug

### ISSUE THREAD

**Issue by pocmo** [mcomella/apt_github_improvements#3]
> As a developer working on issues related to Bugzilla bugs I want to be able to click on text like "Bug 1454444" and it should link to the bug (like on Bugzilla or like using `#1` links to the GitHub issue).

**Comment by mcomella** [comment]
@pocmo A few clarifying questions. Should these links be hoisted to the top of the page, like #1?

Is this about turning existing Bugzilla links into "Bug XXXXX" links? e.g. https://bugzilla.mozilla.org/show_bug.cgi?id=1471868 into [Bug 1471868](https://bugzilla.mozilla.org/show_bug.cgi?id=1471868)? Or is this just about linking "Bug XXXXX"? Or both?

How often do you and others use this? e.g. Since Bugzilla bug numbers are so long and there's no autocomplete, most of the time I'd think I'd just copy-and-paste the URL instead of typing out the number (unless I was copying the bug number from somewhere else, like my branch name). I'm trying to prioritize between this and other issues.

**Comment by pocmo** [comment]
> @pocmo A few clarifying questions. Should these links be hoisted to the top of the page, like #1?

I think that would be useful!

> Is this about turning existing Bugzilla links into "Bug XXXXX" links? e.g. https://bugzilla.mozilla.org/show_bug.cgi?id=1471868 into Bug 1471868? Or is this just about linking "Bug XXXXX"? Or both?

I only intended "Bug XXXX" text to be turned into links.

> How often do you and others use this? e.g. Since Bugzilla bug numbers are so long and there's no autocomplete, most of the time I'd think I'd just copy-and-paste the URL instead of typing out the number (unless I was copying the bug number from somewhere else, like my branch name). I'm trying to prioritize between this and other issues.

Oh, to be honest I have no idea. Probably not that often actually. I copy and paste the URL too. I think "Bug XXXX" only appears later in comments when discussing the issue.
